### ISSUE TITLE
Filename extension is not mandated for CineCanvas XML files

### ISSUE THREAD

**Issue by matmat** [Ymagis/ClairMeta#56]
I can't find any reference to that a filename extension of ".xml" is required. Indeed I have several Interop DCP:s with CineCanvas subtitles with a ".XML" extension (upper case) that play without problems.

https://github.com/Ymagis/ClairMeta/blob/049f459544e9ec08da00d525d346704decd38458/clairmeta/dcp_check_subtitle.py#L184-L187

**Comment by matmat** [comment]
Also this makes check_subtitle_cpl_xml() fail in the following way:

````
2018-12-02 13:00:10,125 - Clairmeta - ERROR - Check unknown error
Traceback (most recent call last):
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_base.py", line 112, in run_check
    check_res = func(*args)
  File "/home/mhm/ClairMeta/clairmeta/dcp_check_subtitle.py", line 205, in check_subtitle_cpl_xml
    namespace = asset['Probe']['NamespaceName']
KeyError: 'Probe'
````

**Comment by matmat** [comment]
Actually the below constraints are the only ones I could find regarding file name constraints.

I.e.: except for VOLINDEX, ASSETMAP, VOLINDEX.xml, ASSETMAP.xml (and the constraint on Interop subtitle directories) files could be named whatever one wants.

Also note that as of ST 429-9:2014 VOLINDEX.xml should not be part of an SMPTE DCP!

**SMPTE**
ST 429-3-2007:
> **6.3 Track File Identity**
> D-Cinema Packaging uses UUID (Universally Unique Identifier) values to link assets. A Track File shall be identified by the Package UID value of its sole Top-level File Package (referred to simply as "Package UID" for the remainder of this section).

> **8.1 File Names and Asset Identity**
> The identity of the asset contained in the file shall be determined from the Package UID (as defined in Section 6.3.1 above) of the Top-Level File Package in the file, and not from the filename or any other environment-specific file identifier, pointer or link.

ST 429-9:2014:
> **A.2 Path**
> (...)
>
>Each path segment, as specified in IETF RFC 3986, shall consist of characters from the set a-z, A-Z, 0-9, “-“ (dash), “_” (underscore) and “.” (period). No segment shall have more than 100 characters, and the value of the Path element shall not exceed 100 characters in length. A Path element value shall have no more than 10 segments. The Path element value shall preserve case (the path and the filename on the filesystem shall have identical case). No two paths in an Asset Map shall have identical value, regardless of case.
>
>Note 2: A relative-path reference cannot start with a "/" character.
>
>Note 3: "." and ".." path segments are allowed.

> **A.4 Asset Map Location**
> (...)
>
>Each Asset Map document shall be a file named “ASSETMAP.xml”.

ST 429-9:2007:
> **A.5 VolumeIndex Location**
> The Volume Index structure shall be in a file named “VOLINDEX.xml”, located in the root directory of the filesystem. When spanning multiple volumes, each volume shall contain exactly one distinct Volume Index structure. A single volume set shall contain a Volume Index structure.

**Interop**

mpeg_ii_am_spec.doc:
> **6.2 Asset Map Location**
> The Asset Map structure shall be contained in a file named ‘ASSETMAP’ located in the root directory of the UDF partition.

> **6.3 VolumeIndex**
> **6.3.1 Location**
> The VolumeIndex parameter shall be contained in a file named ‘VOLINDEX’ located in the root directory of the UDF partition.

> **6.4 Chunk Path Format**
> The path and filename shall conform to the UDF specification.

mpeg_ii_pack_constraints_2v5.doc:
> **7.7 Constraint on Package Structure**
> Each Subtitle file shall be placed in a directory labelled with the UUID of the SubtitleID element of that file
>
> Subtitle file resources (font, image) shall be placed in a directory structure underneath the Subtitle file directory as indicated by the relevant URI that references the resource.

mpeg_ii_track_2v7.doc:
> **7.4 File Names and Asset Identity**
> The names of AS-DCP track files may include the asset id or any other identifier meaningful to the originator.
>
> However, the identity of the asset contained in the file shall be determined from the UMID of the File Package in the file, not from the filename.
